version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Seoul"
    assignees:
      - "bc-lee"
    reviewers:
      - "bc-lee"

